### ISSUE TITLE
Dataset index.txt file contains some corrupted entries

### ISSUE THREAD

**Issue by brutalsavage** [VHellendoorn/Code-LMs#22]
Hi,

Thanks for open sourcing the dataset and PolyCoder.

I'm looking at the dataset: https://zenodo.org/record/6363556/files/index.zip , From the README, it seems that each line in the index.txt should be in the form of `{language}__{organization}__{project}__{full__file__path}\tSHA`, however after parsing there are few lines that seems to be malformed.  

I've attached the malformed entries below

```Line 2673491 : Time.cpp 70ccfc536b2645b27bcf7af2ec94753d70d0d34a16fbb6b4a0cf6b1275fc43a1
Line 2818009 : Upside Down Numbers
Line 2818010 : Upside Down Numbers
Line 2818011 : Upside Down Numbers
Line 2818012 : Upside Down Numbers
Line 2818013 : Upside Down Numbers__main.cpp    0070bf300d9f1bf6ec6533142fbbaa4de8ff65374da8d29e6a85cba5d0ad38df
Line 2818158 : Phone Number Combinations__main.cpp      39ae7219b6377846a3792efcf6db5a9cc1b949652a3cc76edbe5c368f37b90a1
Line 11100410 : .java   3f49f41560cd7a5ea7c2d31120d98dfd2f56da204b6286e099af69d629ba3041```

**Comment by VHellendoorn** [comment]
Hi, thanks for pointing this out! I'm not quite sure what caused the issues here; the first four repeated rows all seem to refer to the same file, which is simply called `Upside Down Numbers`. I imagine invisible or newline characters might be part of the problem. I will see if I can regenerate the file with some extra error checking.

To calibrate whether this is a priority: are these errors blocking you in any way? I imagine since you were able to round up the violating lines, the rest of the file was parsed correctly.

**Comment by brutalsavage** [comment]
Thanks for the quick response, these errors were not blocking me, just wanted to make sure that the file doesn't have any major problem with it. Thanks again
