### ISSUE TITLE
Hugging Face's Hub

### ISSUE THREAD

**Issue by Otavio-Parraga** [VHellendoorn/Code-LMs#26]
Hello! First I would like to congratulate you on the fantastic work done with PolyCoder and the paper. 

Second, I wanted to know if there are plans to release PolyCoder in Hugging Face any time soon? I saw in #13 that in March something about that possibility was commented, but couldn't find it in the hub.

There is still complicated to run the model and adapt it to new scenarios, and making it available by Hugging Face API would facilitate everything.

Thanks!

**Comment by VHellendoorn** [comment]
Thanks for your interest! We definitely hope to make the models available through HF soon; we were initially waiting for support for the NeoX 20B model, since it's based on the same toolkit. That support was recently added in [this PR](https://github.com/huggingface/transformers/pull/16659), so it is quite possible that simply swapping the 20B checkpoints for ours will work out of the box. We have not been able to test this yet because of other summer obligations, but if you have a chance to try that out, that'd be great.

Another option that seems promising is [this repository](https://github.com/zphang/minimal-gpt-neox-20b) that offers a PyTorch-only way to use the 20B checkpoints, which again should almost certainly work exactly the same way with our checkpoints.

Hope this helps; will update here (as well as the README) if we have time to foolproof test one of these routes. But that might be closer to the end of the summer.

**Comment by Otavio-Parraga** [comment]
Thanks for the quick reply!

I'll try both options that you recommended.

Anything new, I'll update here!

**Comment by urialon** [comment]
Hi @Otavio-Parraga ,
Thank you again for your interest in PolyCoder and for your kind words in the previous post!

We really want to release PolyCoder to the HuggingFace Hub, but it seems that none of us has the capacity to do that any time soon.

If you are interested in doing the conversion from GPT-NeoX to HuggingFace - we would really appreciate it, and of course, give you the credit in the README and the Huggingface Hub.

If you are interested in doing this, please let us know, and we can provide additional info. Maybe we can create a Slack channel so that we could communicate more easily if any problem pops up.

Best,
Uri
