### ISSUE TITLE
Code generation fails if more than 1 token in input

### ISSUE THREAD

**Issue by kleag** [VHellendoorn/Code-LMs#30]
Hi, I encounter quite the same problem as in #23 but in a slightly different GPU context. As him/her, I can generate for a single token input but it fails as soon as I add a character to the input.

I had to use singularity instead of docker as I had no root access on this cluster. For this to work, I had to copy the `/gpt-neox` out of the image and bind-mount it in order to have it in read-write mode.

I start it like that:
```
srun --account=xxx --partition=xxx --gres=gpu:1 --time=0-2:00:00 --mem=70G --pty  bash
[xxx@nodexx xxx]$ singularity shell --nv -B $PWD/gpt-neox:/gpt-neox -B $PWD/checkpoints-0-4B:/gpt-neox/checkpoints --writable-tmpfs code-lms-neox_base.sif 
./deepy.py generate.py configs/text_generation.yml checkpoints/configs/local_setup.yml checkpoints/configs/medium.yml
```

The full output including the correct generation for `for` and the failure for `fora` is here: https://paste.libre-service.eu/?f9efce75b3836b4b#BNZq675ihp2LnSqRywMa2Y9EtwzCnu4tZqUwt9o57Q9L

The GPU is a Quadro P5000. Here is the output of nvidia-smi:
```
nvidia-smi
Wed Jun 29 15:14:34 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P5000        On   | 00000000:1B:00.0 Off |                  Off |
| 52%   80C    P0   163W / 180W |   3133MiB / 16278MiB |    100%      Default |
|                               |                      |                  N/A |
```

The GPU memory is never above 2GB (on 16 available).

I have no more ideas to try to solve this problem.

(Note that I first tried to install from source but it failed when installing the requirements)

**Comment by VHellendoorn** [comment]
Hi, sorry to hear this has been a challenge to use. The number one culprit for this particular error you are seeing is a mismatch between the CUDA version on the system and the one PyTorch was built against. The Docker image was built with CUDA 11.1 and the Pytorch version it uses internally also relies on that same version (running `python3 -c "import torch; print(torch.__version__)"` yields `1.8.1+cu111`). When PyTorch is out of sync with the system CUDA toolkit, this error often comes up; I have run into this problem before with several other toolkits. This would explain why the Docker route has no problems but your custom configuration does.

The most straightforward solution tends to be to downgrade CUDA or upgrade PyTorch. Now, last I checked, no designated PyTorch wheels have been released for 11.4 since the wheel for 11.3 [is compatible with CUDA 11.4 already](https://github.com/pytorch/pytorch/issues/75992#issuecomment-1102959704). Unfortunately, when I tried to use the 11.3 wheel with CUDA 11.4 in a separate deployment, a check somewhere deep in the code base caused the program to crash because the CUDA version and Pytorch version did not match exactly, so I found it easier to upgrade CUDA to 11.5 and match PyTorch to that.

So the TL;DR is: this is likely a CUDA/PyTorch mismatch; try to either work in an environment with CUDA 11.1 or upgrade both CUDA and PyTorch to a matching version (11.3 or 11.5). I hope that helps.

**Comment by kleag** [comment]
Hi, thanks for you quick and detailed answer. Unfortunately, there is no CUDA 11.1 available on the cluster I'm working on and I don't think the admins will agree to install that. And I have only access to CUDA 10.0, 11.4 and 11.6. 
Maybe I could install a pytorch compatible with CUDA 11.6? But how can I upgrade PyTorch in the running image? Maybe with `pip install --user`? The problem is that I have no python3.8 outside of the image…
Well, I'm searching a solution. I'll come back with what I found.

**Comment by kleag** [comment]
Hi,
I just notice your sentence: `This would explain why the Docker route has no problems but your custom configuration does.`
But in fact, the crash in inside the docker container (well, converted to singularity).

**Comment by kleag** [comment]
Hi,
I was finally able to run the example by mainly rebasing the docker image. See the referenced pull request.

**Comment by VHellendoorn** [comment]
Hi, I'm glad to hear you were able to get it to run! I am going to hold off on merging that PR because of the stated limitations, but  it does make sense to upgrade the CUDA version and rebase with the original repository sometime soon. In my own experiments, I've rebuilt the image with CUDA 11.5 with fairly few changes, so I may push that version instead. Thanks again!
