### ISSUE TITLE
Great project, however error upon running hugging face implementation/example -  Failed to import transformers.models.gpt_neox.modeling_gpt_neox

### ISSUE THREAD

**Issue by iCosmosNeuroverse** [VHellendoorn/Code-LMs#40]
Hey
 Great project, however error upon running hugging face implementation/example 
 
 Failed to import transformers.models.gpt_neox.modeling_gpt_neox
 
 Tried in python3.7 and python2.9. [with the transformer version advised](https://github.com/vhellendoorn/code-lms#october-2022---polycoder-is-available-on-huggingface).
 
 
![image](https://user-images.githubusercontent.com/82050128/236596130-3a61d337-2799-44bc-a7b0-a55b81ac2850.png)

Any clues?

**Comment by urialon** [comment]
Hi @g0dEngineer ,
Thank you for your interest in our work!

I'm not sure, it looks like a problem with the installation of `transformers` rather than a problem with our model. 

Can you run in the interpreter:
`print(version.parse(transformers.__version__))` and copy the output?

I see that you're running on windows, which might be a problem. Did you try running in a conda environment?

Best,
Uri

**Comment by iCosmosNeuroverse** [comment]
Nevermind, the problem was solved. The version (4.23.0) does not seem to be the issue.
Successfully running on windows.
An odd bug resolved by invoking instead of running the file directly.

**Comment by urialon** [comment]
Great! Glad to hear
