### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by moyix** [VHellendoorn/Code-LMs#5]
First of all, thanks so much for making your model openly available! This is a great resource. We are hoping to use it in some evaluations of [vulnerability repair](https://arxiv.org/abs/2112.02125), and one thing we would like to evaluate is whether the fixes generated by the language model are already present in the training data.

Would it be possible to make the training dataset available somehow? Either the actual data or (if that's too big) the github repositories + commit hashes + filenames would be fine. I can even stop by CMU with a hard drive if uploading it is too inconvenient :)

**Comment by VHellendoorn** [comment]
Thanks for your interest! I've read your valuable work in this new space; glad to hear this project might contribute in some way. 
To help deduplicate with our training corpus, I've pushed a file with the full path and SHA-256 hash of each file in the training data. Please find instructions for getting it in the updated [Data->README](https://github.com/VHellendoorn/Code-LMs/tree/main/Data#polycoder-data).

While I did not record the precise commit hash of each repository at the time of cloning, I hope it's sufficiently informative that the repositories were cloned overnight on October 9-10, 2021. As I mention in the updated README, I'd strongly suggest comparing the hashes of the files against any files you want to use in evaluations just because duplicates abound on GH.

**Comment by moyix** [comment]
Wonderful, thanks very much!
